// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 112);
    lv_obj_set_height(ui_Panel3, 92);
    lv_obj_set_x(ui_Panel3, 60);
    lv_obj_set_y(ui_Panel3, 112);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 112);
    lv_obj_set_height(ui_Panel4, 92);
    lv_obj_set_x(ui_Panel4, -58);
    lv_obj_set_y(ui_Panel4, 112);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_2146430232);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_Image2, -62);
    lv_obj_set_y(ui_Image2, 118);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_459267587);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_Image1, -62);
    lv_obj_set_y(ui_Image1, 118);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_284980415);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_Image4, -62);
    lv_obj_set_y(ui_Image4, 118);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 112);
    lv_obj_set_height(ui_Panel2, 92);
    lv_obj_set_x(ui_Panel2, -58);
    lv_obj_set_y(ui_Panel2, 16);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 112);
    lv_obj_set_height(ui_Panel1, 92);
    lv_obj_set_x(ui_Panel1, 60);
    lv_obj_set_y(ui_Panel1, 16);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_o2_2_png);
    lv_obj_set_width(ui_Image3, 64);
    lv_obj_set_height(ui_Image3, 64);
    lv_obj_set_x(ui_Image3, 61);
    lv_obj_set_y(ui_Image3, 12);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHeartrate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHeartrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeartrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeartrate, -60);
    lv_obj_set_y(ui_LabelHeartrate, 50);
    lv_obj_set_align(ui_LabelHeartrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeartrate, "0");

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_heart_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image5, -61);
    lv_obj_set_y(ui_Image5, 13);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSao2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSao2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSao2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSao2, 62);
    lv_obj_set_y(ui_LabelSao2, 50);
    lv_obj_set_align(ui_LabelSao2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSao2, "0");

    ui_LabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, 60);
    lv_obj_set_y(ui_LabelTime, 92);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "0");

    ui_LabelTouch = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTouch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTouch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTouch, 60);
    lv_obj_set_y(ui_LabelTouch, 134);
    lv_obj_set_align(ui_LabelTouch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTouch, "0");

    ui_ChartHR = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_ChartHR, 200);
    lv_obj_set_height(ui_ChartHR, 120);
    lv_obj_set_x(ui_ChartHR, 40);
    lv_obj_set_y(ui_ChartHR, 2);
    lv_obj_set_align(ui_ChartHR, LV_ALIGN_TOP_LEFT);
    lv_chart_set_type(ui_ChartHR, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartHR, 15);
    lv_chart_set_range(ui_ChartHR, LV_CHART_AXIS_PRIMARY_Y, 0, 150);
    lv_chart_set_axis_tick(ui_ChartHR, LV_CHART_AXIS_PRIMARY_X, 15, 5, 0, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartHR, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartHR, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    ui_ChartHR_series_1 = lv_chart_add_series(ui_ChartHR, lv_color_hex(0xF61212),
                                                                  LV_CHART_AXIS_PRIMARY_Y);
    // static lv_coord_t ui_ChartHR_series_1_array[] = { 0, 0, 20, 40, 80, 80, 40, 70, 90 };
    // lv_chart_set_ext_y_array(ui_ChartHR, ui_ChartHR_series_1, ui_ChartHR_series_1_array);
    lv_obj_set_style_bg_color(ui_ChartHR, lv_color_hex(0x091B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartHR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartHR, lv_color_hex(0x091B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartHR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_ChartHR, lv_color_hex(0x091B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartHR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
