// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Image2;  //bad
lv_obj_t * ui_Image1;  //danger
lv_obj_t * ui_Image4;  //safe
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_LabelHeartrate;
lv_obj_t * ui_Image5;
lv_obj_t * ui_LabelSao2;
lv_obj_t * ui_LabelTime;
lv_obj_t * ui_LabelTouch;
lv_obj_t * ui____initial_actions0;
lv_obj_t * ui_ChartHR;
lv_chart_series_t * ui_ChartHR_series_1;
const lv_img_dsc_t * ui_imgset_o[1] = {&ui_img_o2_png};
const lv_img_dsc_t * ui_imgset_o_[1] = {&ui_img_o2_2_png};

// ///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
//     #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP == 1
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

static ui_driver_motion_t ui_current_motion = SAFE_MODE;

void ui_change_mode(ui_driver_motion_t motion)
{
    ui_current_motion = motion;
}

static void ui_task(void * pvParameter)
{
    while (1) {
        if (ui_current_motion == SAFE_MODE) {
            // Safe mode
            lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN);   /// Flags
            lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);     /// Flags
            
        } else if (ui_current_motion == DANGER_MODE) {
            // Danger mode
            lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN);   /// Flags
            lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN);     /// Flags
        } else if (ui_current_motion == BAD_MODE) {
            // Bad mode
            lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);   /// Flags
            lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN);     /// Flags
            lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN);     /// Flags
        }
        vTaskDelay(500 / portTICK_PERIOD_MS);
    }
}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

    xTaskCreate(ui_task, "ui_task", 4096, NULL, 1, NULL);
}
