// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

typedef enum {
    SAFE_MODE,
    BAD_MODE,
    DANGER_MODE,
} ui_driver_motion_t;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_LabelHeartrate;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_LabelSao2;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_LabelTouch;
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t * ui_ChartHR;
extern lv_chart_series_t * ui_ChartHR_series_1;

LV_IMG_DECLARE(ui_img_2146430232);    // assets\biaoqing-yigaiming-zhagehua_keai.png
LV_IMG_DECLARE(ui_img_459267587);    // assets\biaoqing-yigaiming-zhagehua_shengqi.png
LV_IMG_DECLARE(ui_img_284980415);    // assets\biaoqing-yigaiming-zhagehua_ziya.png
LV_IMG_DECLARE(ui_img_o2_2_png);    // assets\o2_2.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets\heart.png
LV_IMG_DECLARE(ui_img_o2_png);    // assets\o2.png

LV_FONT_DECLARE(ui_font_PHFont16);
LV_FONT_DECLARE(ui_font_PHFont18);
LV_FONT_DECLARE(ui_font_PHFont20);
LV_FONT_DECLARE(ui_font_PHFont22);
LV_FONT_DECLARE(ui_font_PHFont24);
LV_FONT_DECLARE(ui_font_PHFont26);
LV_FONT_DECLARE(ui_font_PHFont30);

void ui_init(void);
void ui_change_mode(ui_driver_motion_t motion);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
